name: munijCI

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run EsLint
        run: npx eslint "A01781341/*.js"

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Package App
        run: |
          zip print_name.zip A01781341/*.js

  dockerize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Docker Image
        run: |
          docker build . -t express-app
      - name: Run docker Image
        run: |
          docker run -p express-app

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install 
          npm test

