name: munijCI

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install --no-optional

      - name: Run EsLint
        run: npx eslint "A01781341/*.js"

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Print Directory Contents
        run: ls A01781341
      - name: Package App
        run: |
          zip create_port.zip A01781341/*.js

  dockerize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Docker Image
        run: |
          docker build -f ./Dockerfile -t express-app:latest .
      - name: Run docker Image
        run: |
          docker run -p 8080:3000 express-app:latest

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install 
          npm test

